[package]
name = "packet_derive"
version = "0.1.0"
authors = ["Griffin T <a12345678910ster@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.8"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
