[package]
name = "packet_derive"
version = "0.1.0"
authors = ["Griffin T <a12345678910ster@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits"] }